use_frameworks!

platform :ios, '8.0'

target 'componentTool_Example' do
  pod 'componentTool', :path => '../'

  target 'componentTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
